// app/legal/terms-of-service/page.js
import React from 'react';

/**
 * Terms of Service page component.
 * Displays the terms and conditions for using Flight Lens.
 * @returns {JSX.Element} The Terms of Service page.
 */
export default function TermsOfServicePage() {
	return (
		<article className='prose lg:prose-xl max-w-none'>
			<h2 className='text-2xl font-semibold mb-6 text-gray-700'>
				Terms of Service
			</h2>

			<p className='mb-4'>Effective Date: {new Date().toLocaleDateString()}</p>

			<p className='mb-4'>
				Please read these Terms of Service ("Terms", "Terms of Service")
				carefully before using the Flight Lens application (the "Service")
				operated by us ("us", "we", or "our"). Your access to and use of the
				Service is conditioned on your acceptance of and compliance with these
				Terms. These Terms apply to all visitors, users, and others who access
				or use the Service. By accessing or using the Service you agree to be
				bound by these Terms. If you disagree with any part of the terms then
				you may not access the Service.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Use of Service
			</h3>
			<p className='mb-4'>
				Flight Lens provides AI-generated flight and aircraft information for
				informational purposes only. The data provided is generated by Google's
				Gemini API and is based on the flight number you provide. While we
				strive to provide plausible and seemingly accurate information, we do
				not guarantee the accuracy, completeness, timeliness, or reliability of
				any information provided by the Service. The information is not
				real-time flight data from official airline or aviation authorities and
				should not be used for navigation, safety-critical decisions, or any
				purpose where inaccurate information could lead to harm, loss, or
				damage.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				User Conduct
			</h3>
			<p className='mb-4'>You agree not to use the Service:</p>
			<ul className='list-disc pl-6 mb-4 space-y-2'>
				<li>
					In any way that violates any applicable national or international law
					or regulation.
				</li>
				<li>
					For the purpose of exploiting, harming, or attempting to exploit or
					harm minors in any way by exposing them to inappropriate content or
					otherwise.
				</li>
				<li>
					To transmit, or procure the sending of, any advertising or promotional
					material, including any "junk mail," "chain letter," "spam," or any
					other similar solicitation.
				</li>
				<li>
					To impersonate or attempt to impersonate Flight Lens, a Flight Lens
					employee, another user, or any other person or entity.
				</li>
				<li>
					In any way that infringes upon the rights of others, or in any way is
					illegal, threatening, fraudulent, or harmful, or in connection with
					any unlawful, illegal, fraudulent, or harmful purpose or activity.
				</li>
				<li>
					To engage in any other conduct that restricts or inhibits anyone's use
					or enjoyment of the Service, or which, as determined by us, may harm
					or offend Flight Lens or users of the Service or expose them to
					liability.
				</li>
			</ul>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Intellectual Property
			</h3>
			<p className='mb-4'>
				The Service and its original content (excluding content provided by
				users or generated by third-party APIs like Google Gemini), features,
				and functionality are and will remain the exclusive property of Flight
				Lens and its licensors. The Service is protected by copyright,
				trademark, and other laws of both the [Your Country - Placeholder] and
				foreign countries. Our trademarks and trade dress may not be used in
				connection with any product or service without the prior written consent
				of Flight Lens.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Third-Party Services and Data
			</h3>
			<p className='mb-4'>
				The Service relies on the Google Gemini API to generate flight and
				aircraft information. Your use of this information is also subject to
				Google's terms of service for their APIs. We are not responsible for the
				accuracy, content, or availability of information provided by
				third-party services.
			</p>
			<p className='mb-4'>
				The Service may display advertisements from third parties, such as
				Google AdSense. We are not responsible for the content of these
				advertisements or the practices of third-party advertisers. Your
				interactions with any advertisers found on or through the Service,
				including payment and delivery of goods or services, and any other
				terms, conditions, warranties, or representations associated with such
				dealings, are solely between you and such advertisers.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Disclaimer of Warranties
			</h3>
			<p className='mb-4'>
				The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make
				no warranties, expressed or implied, regarding the operation or
				availability of the Service, or the information, content, or materials
				included therein. You expressly agree that your use of the Service is at
				your sole risk. We do not warrant that the Service will be
				uninterrupted, error-free, or free of viruses or other harmful
				components. The flight and aircraft information provided is AI-generated
				and for informational and entertainment purposes only. It is not a
				substitute for official flight data and should not be relied upon for
				critical decisions.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Limitation of Liability
			</h3>
			<p className='mb-4'>
				In no event shall Flight Lens, nor its directors, employees, partners,
				agents, suppliers, or affiliates, be liable for any indirect,
				incidental, special, consequential or punitive damages, including
				without limitation, loss of profits, data, use, goodwill, or other
				intangible losses, resulting from (i) your access to or use of or
				inability to access or use the Service; (ii) any conduct or content of
				any third party on the Service; (iii) any content obtained from the
				Service; and (iv) unauthorized access, use or alteration of your
				transmissions or content, whether based on warranty, contract, tort
				(including negligence) or any other legal theory, whether or not we have
				been informed of the possibility of such damage, and even if a remedy
				set forth herein is found to have failed of its essential purpose.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Indemnification
			</h3>
			<p className='mb-4'>
				You agree to defend, indemnify and hold harmless Flight Lens and its
				licensee and licensors, and their employees, contractors, agents,
				officers and directors, from and against any and all claims, damages,
				obligations, losses, liabilities, costs or debt, and expenses (including
				but not limited to attorney's fees), resulting from or arising out of a)
				your use and access of the Service, or b) a breach of these Terms.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Governing Law
			</h3>
			<p className='mb-4'>
				These Terms shall be governed and construed in accordance with the laws
				of [Your Jurisdiction - Placeholder, e.g., State of California, United
				States], without regard to its conflict of law provisions. Our failure
				to enforce any right or provision of these Terms will not be considered
				a waiver of those rights. If any provision of these Terms is held to be
				invalid or unenforceable by a court, the remaining provisions of these
				Terms will remain in effect. These Terms constitute the entire agreement
				between us regarding our Service, and supersede and replace any prior
				agreements we might have had between us regarding the Service.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Changes to Terms of Service
			</h3>
			<p className='mb-4'>
				We reserve the right, at our sole discretion, to modify or replace these
				Terms at any time. If a revision is material we will provide at least 30
				days' notice prior to any new terms taking effect. What constitutes a
				material change will be determined at our sole discretion. By continuing
				to access or use our Service after any revisions become effective, you
				agree to be bound by the revised terms. If you do not agree to the new
				terms, you are no longer authorized to use the Service.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Contact Us
			</h3>
			<p className='mb-4'>
				If you have any questions about these Terms, please contact us at:
				https://www.linkedin.com/in/akm85/
			</p>
		</article>
	);
}
