// app/legal/privacy-policy/page.js
import React from 'react';

/**
 * Privacy Policy page component.
 * Displays the privacy policy information for Flight Lens.
 * @returns {JSX.Element} The Privacy Policy page.
 */
export default function PrivacyPolicyPage() {
	return (
		<article className='prose lg:prose-xl max-w-none'>
			<h2 className='text-2xl font-semibold mb-6 text-gray-700'>
				Privacy Policy
			</h2>

			<p className='mb-4'>Effective Date: {new Date().toLocaleDateString()}</p>

			<p className='mb-4'>
				Welcome to Flight Lens ("we," "us," or "our"). We are committed to
				protecting your privacy. This Privacy Policy explains how we collect,
				use, disclose, and safeguard your information when you use our
				application, Flight Lens. Please read this privacy policy carefully. If
				you do not agree with the terms of this privacy policy, please do not
				access the application.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Information We Collect
			</h3>
			<p className='mb-4'>
				Flight Lens is designed to provide flight and aircraft information based
				on user input (e.g., a flight number). We do not require users to create
				accounts or provide personal identification information to use the core
				functionality of the app.
			</p>
			<ul className='list-disc pl-6 mb-4 space-y-2'>
				<li>
					<strong>Flight Number Input:</strong> We collect the flight number you
					enter to fetch and display relevant flight and aircraft data. This
					input is processed by the Google Gemini API to generate the
					information you see.
				</li>
				<li>
					<strong>Usage Data (via Vercel Analytics and Speed Insights):</strong>{' '}
					We use Vercel Analytics and Vercel Speed Insights to collect anonymous
					data about how users interact with our application. This may include
					information such as page views, session duration, browser type,
					operating system, and general geographic location (e.g., country).
					This data is aggregated and anonymized and helps us understand user
					behavior, improve application performance, and enhance user
					experience. Vercel's privacy policy can be found on their website.
				</li>
				<li>
					<strong>Google AdSense:</strong> We use Google AdSense to display
					advertisements on Flight Lens. Google AdSense may use cookies and web
					beacons to collect information about your visits to this and other
					websites in order to provide relevant advertisements about goods and
					services of interest to you. Google's use of advertising cookies
					enables it and its partners to serve ads to your users based on their
					visit to your sites and/or other sites on the Internet. Users may opt
					out of personalized advertising by visiting{' '}
					<a
						href='https://www.google.com/settings/ads'
						target='_blank'
						rel='noopener noreferrer'
						className='text-purple-600 hover:underline'
					>
						Ads Settings
					</a>
					.
				</li>
			</ul>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				How We Use Your Information
			</h3>
			<p className='mb-4'>
				We use the information we collect in the following ways:
			</p>
			<ul className='list-disc pl-6 mb-4 space-y-2'>
				<li>To provide, operate, and maintain Flight Lens.</li>
				<li>
					To process your flight number queries and display relevant information
					generated by the AI.
				</li>
				<li>
					To understand and analyze how you use our application through
					aggregated and anonymized analytics data.
				</li>
				<li>
					To improve the functionality, performance, and user experience of
					Flight Lens.
				</li>
				<li>To display advertisements through Google AdSense.</li>
			</ul>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Sharing Your Information
			</h3>
			<p className='mb-4'>
				We do not sell, trade, or otherwise transfer your personally
				identifiable information to outside parties. This does not include
				trusted third parties who assist us in operating our application,
				conducting our business, or servicing you, so long as those parties
				agree to keep this information confidential. We may also release your
				information when we believe release is appropriate to comply with the
				law, enforce our site policies, or protect ours or others' rights,
				property, or safety.
			</p>
			<p className='mb-4'>Specifically:</p>
			<ul className='list-disc pl-6 mb-4 space-y-2'>
				<li>
					<strong>Google Gemini API:</strong> The flight numbers you enter are
					sent to the Google Gemini API to generate flight information. Google's
					handling of this data is subject to their API terms of service and
					privacy policy.
				</li>
				<li>
					<strong>Vercel:</strong> Anonymized usage data is collected by Vercel
					for analytics and performance monitoring, subject to Vercel's privacy
					policy.
				</li>
				<li>
					<strong>Google AdSense:</strong> Information may be collected by
					Google AdSense for the purpose of serving personalized ads. You can
					manage your ad preferences through Google's Ad Settings.
				</li>
			</ul>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Data Security
			</h3>
			<p className='mb-4'>
				We take reasonable measures to help protect the information we collect
				from loss, theft, misuse, and unauthorized access, disclosure,
				alteration, and destruction. However, please be aware that despite our
				efforts, no security measures are perfect or impenetrable, and no method
				of data transmission can be guaranteed against any interception or other
				type of misuse.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Cookies and Tracking Technologies
			</h3>
			<p className='mb-4'>
				Flight Lens itself does not directly set cookies for tracking users.
				However, third-party services we use, such as Google AdSense and Vercel
				Analytics, may use cookies or similar tracking technologies to collect
				information. You can typically remove or reject cookies via your browser
				settings. To do this, follow the instructions provided by your browser
				(usually located within the "settings," "help," "tools," or "edit"
				facility). Many browsers are set to accept cookies until you change your
				settings.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Children's Privacy
			</h3>
			<p className='mb-4'>
				Flight Lens is not intended for use by children under the age of 13. We
				do not knowingly collect personal information from children under 13. If
				we become aware that a child under 13 has provided us with personal
				information, we will take steps to delete such information.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Changes to This Privacy Policy
			</h3>
			<p className='mb-4'>
				We may update this Privacy Policy from time to time. We will notify you
				of any changes by posting the new Privacy Policy on this page and
				updating the "Effective Date" at the top. You are advised to review this
				Privacy Policy periodically for any changes. Changes to this Privacy
				Policy are effective when they are posted on this page.
			</p>

			<h3 className='text-xl font-semibold mt-6 mb-3 text-gray-700'>
				Contact Us
			</h3>
			<p className='mb-4'>
				If you have any questions about this Privacy Policy, please contact us
				at: https://www.linkedin.com/in/akm85/
			</p>
		</article>
	);
}
